#!/bin/bash
# This Script is to get SWM surfaces from white surface.


SUBJECTS_DIR=/media/imgdb_mnt/Personal/SUBIN/LIST/LaminarQSM
cd $SUBJECTS_DIR

for subj in subj3 #subj4_TX #subj1 subj2 subj3 subj5 #subj4_TX
do
	subjfs="coregR2S_"$subj	
	out_dir=$SUBJECTS_DIR/$subjfs/surface_outputs_01
	# if SRC_image is trilinear, will be automatically changed to surface_outputs_01_interp-trilinear


	for mod in xsepnet_r2s_pos xsepnet_r2s_neg #r2star #manualROIedit4 #manualROIedit2 # cosmos xp xn #slice138 #slice112_enlarged slice133 #qsmnet medi #slice112 slice112_more #qsmnet medi wmparcvs T1 cosmos V1_vs V2_vs multiBA_vs #wmparc
	do
		if [[ $mod = "T1" ]]; then
			src_image=$SUBJECTS_DIR/$subjfs"_T1".nii
			intmethod="trilinear"
			out_dir=$SUBJECTS_DIR/$subjfs/surface_outputs_01_interp-trilinear

		elif [[ $mod = "wmparcvs" ]]; then
			src_image=$SUBJECTS_DIR/$subjfs"_wmparc-vsharpmasked".nii
			intmethod="nearest"

		elif [[ $mod = "wmparc" ]]; then
			src_image=$SUBJECTS_DIR/$subjfs/mri/wmparc.mgz
			intmethod="nearest"

		elif [[ $mod = "manualROI" ]]; then
			src_image=$SUBJECTS_DIR/manual_ROI_masks/$subjfs"_manualROI".nii
			intmethod="nearest"
		elif [[ $mod = "manualROIedit2" ]]; then
			src_image=$SUBJECTS_DIR//manual_ROI_masks/$subjfs"_manualROIedit2".nii
			intmethod="nearest"
		elif [[ $mod = "manualROIedit3" ]]; then
			src_image=$SUBJECTS_DIR/manual_ROI_masks/further_edited_insular/$subjfs"_manualROIedit3".nii
			intmethod="nearest"
		elif [[ $mod = "manualROIedit4" ]]; then
			src_image=$SUBJECTS_DIR/manual_ROI_masks/further_edited_for_figure/$subjfs"_manualROIedit4".nii
			intmethod="nearest"


		elif [[ $mod = "cosmos" ]]; then
			src_image=$SUBJECTS_DIR/$subj"_cosmos_ro-os".nii
			intmethod="trilinear"
			out_dir=$SUBJECTS_DIR/$subjfs/surface_outputs_01_interp-trilinear

		elif [[ $mod = "xp" ]]; then
			src_image=$SUBJECTS_DIR/$subj"_xp-cosmos-edit_ro-os".nii
			intmethod="trilinear"
			out_dir=$SUBJECTS_DIR/$subjfs/surface_outputs_01_interp-trilinear

		elif [[ $mod = "xn" ]]; then
			src_image=$SUBJECTS_DIR/$subj"_xn-cosmos-edit_ro-os".nii
			intmethod="trilinear"
			out_dir=$SUBJECTS_DIR/$subjfs/surface_outputs_01_interp-trilinear

		elif [[ $mod = "r2star" ]]; then
			src_image=$SUBJECTS_DIR/$subj"_r2star_ro-os".nii
			intmethod="trilinear"
			out_dir=$SUBJECTS_DIR/$subjfs/surface_outputs_01_interp-trilinear

		elif [[ $mod = "xsepnet_r2s_pos" ]]; then
			src_image=$SUBJECTS_DIR/xsepnet_data/"testsubj_xsepnet_r2s_pred-xpos".nii
			intmethod="trilinear"
			out_dir=$SUBJECTS_DIR/$subjfs/surface_outputs_01_interp-trilinear
		elif [[ $mod = "xsepnet_r2s_neg" ]]; then
			src_image=$SUBJECTS_DIR/xsepnet_data/"testsubj_xsepnet_r2s_pred-xneg".nii
			intmethod="trilinear"
			out_dir=$SUBJECTS_DIR/$subjfs/surface_outputs_01_interp-trilinear

		else
			break
		fi

			for frac in -0.1 -0.2 -0.3 -0.4 -0.5 -0.6 -0.7 -0.8 -0.9 -1
			do

			h="lh"
			mri_vol2surf --src $src_image \
					--out $out_dir/$subj"_SWM_"$h"_"$mod"_frac"$frac.mgh \
					--out_type mgh \
					--hemi $h \
					--projfrac $frac --regheader $subjfs --surf equi1.0.pial --interp $intmethod
						
			h="rh"
			mri_vol2surf --src $src_image \
					--out $out_dir/$subj"_SWM_"$h"_"$mod"_frac"$frac.mgh \
					--out_type mgh \
					--hemi $h \
					--projfrac $frac --regheader $subjfs  --surf equi1.0.pial --interp $intmethod
						
			done
	done	
done
