


% Define Directories:
dirs.DDRIVE =  'D:\subindata\KUH\';
    dirs.phs_tissue = [dirs.DDRIVE '5_LPSRAS_considered\00_ALLECHO_VERSIONS_00\' '4_3_QSMnet_input_phstissue_qs_LPS'];    
    dirs.output     = [dirs.DDRIVE ''];

% This file is generated by SEPIA version: v0.8.1.1
% add general Path
sepia_addpath

subjects = {'BBB_01'};%,'BBB_02','BBB_03','BBB_04','BBB_06','BBB_07','BBB_08','BBB_09','BBB_10'}; %,'BBB_11','BBB_12','BBB_15','BBB_16','BBB_17','BBB_18','BBB_20','BBB_24','BBB_34','BBB_35','BBB_36','BBB_37','BBB_38','BBB_39','BBB_40','BBB_41','BBB_42','BBB_43','BBB_44','BBB_45','BBB_46','BBB_47','BBB_48','BBB_49','BBB_50','BBB_51','BBB_52','BBB_53','BBB_55','BBB_56','BBB_57','BBB_58','BBB_59','BBB_60','BBB_61','BBB_63','BBB_65','BBB_66','BBB_67','BBB_68','BBB_70','BBB_71','BBB_74','BBB_75','HY01','HY02','HY03','HY06','HY07','HY08','HY10','HY12','HY13','HY14','HY15','HY16','HY18','HY20','HY21','HY22','HY23','HY24','HY25','HY26','HY27','HY28','HY29','HY30','HY31','HY33','HY34','HY35','KK01','KK02','KK03','KK04','KK05','KK06','KK07','KK08','KK09','KK10','KK11','KK12','KK13','KK14','KK16','KK17','KK18','KK19','KK20','KK22','KK23','KK24','KK25','KK26','KK27','KK29','KK30','KK32','KK33','KK34','KK35','KK36','KK37','KK39','KK40','KK41','KK42','KK43','KK44','KK47','KK50','KK51',...
%      'BBB_19','BBB_21','BBB_22','BBB_23','BBB_25','BBB_26','BBB_27','BBB_28','BBB_29','BBB_30','BBB_31','BBB_32','BBB_33','BBB_54','BBB_62','BBB_64','BBB_69','BBB_72','BBB_73','HY04','HY11','HY32','KK28','KK31',...
%      'QSM001','QSM004','QSM008','QSM009','QSM010','QSM012','QSM018','QSM032','QSM037','QSM038','QSM039','QSM040','QSM041','QSM042','QSM046','QSM049','QSM051','QSM053','QSM055','QSM057','QSM063','QSM070','QSM071','QSM075','QSM077','QSM078','QSM079','QSM082','QSM083','QSM086','QSM087','QSM092','QSM095','QSM100','QSM101','QSM103','QSM105','QSM108','QSM109','QSM113','QSM119','QSM120','QSM121','QSM123','QSM125','QSM126','QSM148','QSM149','QSM150','QSM152','QSM153','QSM155','QSM161','QSM162','QSM164','QSM166','QSM167','QSM169','QSM173','QSM175','QSM178','QSM181','QSM183','QSM184','QSM185','QSM189','QSM191','QSM195','QSM199','QSM201','QSM210','QSM211','QSM213','QSM222','QSM225','QSM228','QSM230','QSM231','QSM238','QSM242','QSM243','QSM248','QSM249','QSM251','QSM252','QSM262','QSM274','QSM275','QSM277','QSM280','QSM281','QSM282','QSM283','QSM284','QSM290','QSM292','QSM301','QSM302','QSM303','QSM304','QSM308','QSM309','QSM310','QSM314','QSM315','QSM316','QSM323','QSM324','QSM325','QSM329','QSM330','QSM333','QSM334','QSM343','QSM344','QSM345','QSM346'};


for idx = 1:length(subjects)
    
    subj = subjects{idx};
    
    % Input/Output filenames
    input(1).name = ''; %['D:\subindata\KUH\7_SEPIA\' subj '_Phase_resampled.nii']; 
    input(2).name = ['D:\subindata\KUH\7_SEPIA\' subj '_Magnitude_resampled.nii']; 
    input(3).name = '' ;
    input(4).name = ['D:\subindata\KUH\SEPIA_practice_with_recon_only\Subin_input_header.mat'] ;
    output_basename = [dirs.output '\' subj '_']; 
    mask_filename = [''] ;
    
    % General algorithm parameters
    algorParam=struct();

    % QSM algorithm parameters
    algorParam.qsm.reference_tissue = 'CSF' ;
    algorParam.qsm.method = 'MEDI' ;
    algorParam.qsm.lambda = 1000 ;
    algorParam.qsm.wData = 0 ;
    algorParam.qsm.percentage = 90 ;
    algorParam.qsm.zeropad = [0  0  0] ;
    algorParam.qsm.isSMV = 1 ;
    algorParam.qsm.radius = 5 ;
    algorParam.qsm.merit = 1 ;
    algorParam.qsm.isLambdaCSF = 1 ;
    algorParam.qsm.lambdaCSF = 100 ;
    
    sepiaIO(input,output_basename,mask_filename,algorParam);
end



% DICOM are loaded LPS orientation.
% FS/nii files are RAS orientation.

%% Keep in LPS orientation :
% - mag_echo_1iso
% - Unwrapped_Phase_me
% - Mask
% - Tissuephase_me
% - phs_tissue


MEDI_set_path

if exist(fname_ifield_mat)==2 % a file with extension .mat or etc
    load(fname_ifield_mat)
else
    disp(' loading SIEMENS dicom data... ' )
    [iField,voxel_size,matrix_size,CF,delta_TE,TE,B0_dir]=Read_Siemens_DICOM_m_subin(orig_qsm_dcm_dir_subj);
    save(fname_ifield_mat) 
end

for ii=1:size(iField,4)
    ft_im(:,:,:,ii)=fft3c(iField(:,:,:,ii));
end
ft_im = ft_im(:,:,:,1:6);
im_re = resize_im_subin(voxel_size',matrix_size,ft_im,TE);
spatial_res= [1 1 1];

matrix_mod = size(im_re(:,:,:,1));
if length(TE)>5
    iMag = sqrt(sum(abs(im_re(:,:,:,1:end-2)).^2,4));
else
    iMag = sqrt(sum(abs(im_re).^2,4));
end

% Don't need to use for now bc already have fname_mag_echo_1iso made.
% Do i need to make ref image fs as well?? src should prob adjust to qs.
mag_echo_1iso = sqrt(sum(abs(im_re(:,:,:,options.echo_for_coreg)).^2,4));
    mag_echo_1iso_nii = make_nii(mag_echo_1iso, [1 1 1], [120 120 60]);
    save_nii(mag_echo_1iso_nii, fname_mag_echo_1iso);

Mask = BET(iMag,matrix_mod,spatial_res);
    %Mask=imerode(imdilate(imerode(Mask,strel('disk',2)),strel('disk',2)),strel('disk',2));
    
    
[N(1), N(2), N(3), num_dir] = size(angle(im_re(:,:,:,:))) %%***
gyro = 2*pi*42.58;
B0 = CF/(gyro/2/pi*10^6);       


% [Unwrapped_Phase_me, Laplacian]=MRPhaseUnwrap(angle(im_re(:,:,:,:)),'voxelsize',spatial_res,'padsize',[12 12 12]); %%***
% Unwrapped_Phase_me=sum(Unwrapped_Phase_me,4);
% 
% [TissuePhase_me,NewMask]=V_SHARP(Unwrapped_Phase_me,Mask,'voxelsize',spatial_res);
% 
% Phase_me = TissuePhase_me / (sum(TE)*B0*gyro); %%***
% phs_tissue = -Phase_me;
% save(fname_final, 'phs_tissue') 

[Unwrapped_Phase_me_allecho, Laplacian]=MRPhaseUnwrap(angle(im_re(:,:,:,:)),'voxelsize',spatial_res,'padsize',[12 12 12]);
    Unwrapped_Phase_me_allecho=sum(Unwrapped_Phase_me_allecho,4);
    Unwrapped_Phase_me_ALL_neg_nii = make_nii(-Unwrapped_Phase_me_allecho, [1 1 1], [120 120 60]);
    save_nii(Unwrapped_Phase_me_ALL_neg_nii, fname_unwrappedphase_ALL_neg)    
    
[TissuePhase_me_allecho,NewMask]=V_SHARP(Unwrapped_Phase_me_allecho,Mask,'voxelsize',spatial_res);
    TissuePhase_me_ALL_neg_nii = make_nii(-TissuePhase_me_allecho, [1 1 1], [120 120 60]);
    save_nii(TissuePhase_me_ALL_neg_nii, fname_tissuephase_ALL_neg)
    
Phase_me_all_echo = -TissuePhase_me_allecho / (sum(TE)*B0*gyro);
    Phase_me_ALL_nii = make_nii(Phase_me_all_echo, [1 1 1], [120 120 60]);
    save_nii(Phase_me_ALL_nii, fname_phstissue_d_ALL);

phs_tissue = Phase_me_all_echo;
    save(fname_final, 'phs_tissue')


%% 
   
%  ===============NO NEED TO RE-DO BELOW PROCESSES =============================================    
% % *************DO BELOW AFTER FREESURFER IS DONE, BECAUSE NEED TO BRING FS-SPACE T1 AND MASKS*******************
% %% Change from RAS to LPS orientation:
% % - T1_fs and wmparcmask_fs --> T1_fs_LPS, wmparc_fs_LPS
% 
% T1 = load_untouch_nii(fname_t1);
% wmparc = load_untouch_nii(fname_wmparc); % FS에서 생성된 파일은 load_nii로 제데로 불러와지지만,
%                                          % spm을 거친 파일은 모두 load_untouch_nii로만 불러올수있음.
%                                          % 근데 이번에는 load_nii로 불러오면 에러뜨므로 ㅠㅠ untouch.
%                                              
%     % untouch로 불러왔기때문에 axial대신 coronal로 load됨. 
%     % 아래로 axis 맞추면 LAI로 됨.
%     t1_ro = permute(T1.img, [1 3 2]);
%     wmparc_ro = permute(wmparc.img, [1 3 2]);
% 
%     % 다음을 통해 LAI--> LAS로 바꿈
%     t1_las = zeros(size(t1_ro));
%     wmparc_las = zeros(size(wmparc_ro));
%     for rr = 0:255
%         t1_las(:,:,256-rr) = t1_ro(:,:,rr+1);
%         wmparc_las(:,:,256-rr) = wmparc_ro(:,:,rr+1);
%     end
% 
%    % LAS-->LPS: 
%    t1_lps = fliplr(t1_las);
%    wmparc_lps = fliplr(wmparc_las);
% 
%    % fs_LPS로 저장 (coregister 준비)
%    t1_fs_lps_nii = make_nii(t1_lps,[1 1 1],[128 128 128]);
%        save_nii(t1_fs_lps_nii, fname_t1_ro);
%    wmparc_fs_lps_nii = make_nii(wmparc_lps,[1 1 1],[128 128 128]);
%        save_nii(wmparc_fs_lps_nii, fname_wmparc_ro);
% 
% 
% 
% %% Change from LPS to RAS orientation:
% % - vsharp_nii
% % - CSF mask and R2 map
% 
% % - qsm-coregistered fsmask ( automatically un-zeropadded while coregistering to qsm.RAS-transformed in postprocessing, not here)
% 
% %=============ADDED STEPS===================================
%     
% 1. Coregister the fsspace_isot1 to 1iso mag_e1 using NEARESTNEIGHBOR 
%    (To make a FS_ROIMask that is matched to the im_re/UnwrappedPhase_me):
%    (fs_LPS --> qs_LPS) 
matlabbatch{1}.spm.spatial.coreg.estwrite.ref = {strcat(fname_mag_echo_1iso, ',1')}; 
matlabbatch{1}.spm.spatial.coreg.estwrite.source = {strcat(fname_t1_ro,',1')}; 
matlabbatch{1}.spm.spatial.coreg.estwrite.other = {strcat(fname_wmparc_ro,',1')};
matlabbatch{1}.spm.spatial.coreg.estwrite.eoptions.cost_fun = 'nmi'; %'mi', 'ecc'
matlabbatch{1}.spm.spatial.coreg.estwrite.eoptions.sep = [4 2];
matlabbatch{1}.spm.spatial.coreg.estwrite.eoptions.tol = [0.02 0.02 0.02 0.001 0.001 0.001 0.01 0.01 0.01 0.001 0.001 0.001];
matlabbatch{1}.spm.spatial.coreg.estwrite.eoptions.fwhm = [7 7];
matlabbatch{1}.spm.spatial.coreg.estwrite.roptions.interp = 0;
matlabbatch{1}.spm.spatial.coreg.estwrite.roptions.wrap = [0 0 0];
matlabbatch{1}.spm.spatial.coreg.estwrite.roptions.mask = 0;
matlabbatch{1}.spm.spatial.coreg.estwrite.roptions.prefix = 'magcoreg_nn_';
spm_jobman('run', matlabbatch);  
movefile([dirs.ro_fsmask '\magcoreg_nn_' subj '_wmparc' '_qs_LPS' '.nii'], dirs.mag_coreg_fsmask)
% 
% 
% % 2. Make CSF maps (and Re-orient to QSM space (...'_ro'):
% %    R2* map needed for ventricular CSF mask
% %    Ventricular CSF mask for zero referencing 
%      R2s = arlo(TE(:), abs(im_re(:,:,:,:)));
%      Mask_CSF = extract_CSF(R2s, NewMask, voxel_size);      
%             
%             % qsLPS-->qs_RAS transformation
%             Mask_CSF_lps2ras = flipud(fliplr(Mask_CSF));
%             R2s_lps2ras = flipud(fliplr(R2s));
            NewMask_lps2ras = flipud(fliplr(NewMask));            
%            
%             Mask_CSF_lps2ras = int32(Mask_CSF_lps2ras);
            NewMask_lps2ras = int32(NewMask_lps2ras);
%             
%             % qs_RAS로 저장
%             mask_csf_nii = make_nii(Mask_CSF_lps2ras, [1 1 1],[120 120 60]);
%             save_nii(mask_csf_nii, ['D:\subindata\KUH\5_LPSRAS_considered\4_4_CSF_R2_maps_qs_RAS\' subj '_CSFmask_6e_qs_RAS.nii'])
%             
%             R2_nii = make_nii(R2s_lps2ras, [1 1 1], [120 120 60]);
%             save_nii(R2_nii, ['D:\subindata\KUH\5_LPSRAS_considered\4_4_CSF_R2_maps_qs_RAS\' subj '_R2_6e_qs_RAS.nii'])
%       
            % have to reload fname_betmask_vsharp bc overwritten by .mat file
            fname_betmask_vsharp = [dirs.DDRIVE '5_LPSRAS_considered\00_ALLECHO_VERSIONS_00\' '4_2_betmasks_vsharp_qs_RAS' '\' subj '_vsharp_betmask' '_qs_RAS_ALLECHO.nii'];
            vsharp_nii = make_nii(NewMask_lps2ras, [1 1 1], [120 120 60]);
            save_nii(vsharp_nii, fname_betmask_vsharp)
