#!/bin/bash
export FREESURFER_HOME=/home/list3/Personal_Folder/Subin/subin_downloads/freesurfer
source $FREESURFER_HOME/SetUpFreeSurfer.sh

hdrimg_dir=/home/list3/Personal_Folder/Subin/KUH/1_converted
output_dir=/home/list3/Personal_Folder/Subin/KUH/1_converted_nii_b

for subj in HY01 HY02 KK01 KK02 #BBB_01 BBB_02 BBB_03 BBB_04 BBB_05 BBB_06 BBB_07 BBB_08 BBB_09 BBB_10 BBB_11 BBB_12 BBB_13 BBB_14 BBB_15 BBB_16 BBB_17 BBB_18 BBB_19 BBB_20 BBB_21 BBB_22 BBB_23 BBB_24 BBB_25 BBB_26 BBB_27 BBB_28 HY01 HY02 HY03 HY04 HY06 HY07 HY08 HY10 HY11 HY12 HY13 HY14 HY15 HY16 HY18 HY19 HY20 HY21 HY22 HY23 HY24 HY25 HY26 HY27 HY28 HY29 HY30 HY31 HY32 HY33 HY34 HY35 KK01 KK02 KK03 KK04 KK05 KK06 KK07 KK08 KK09 KK10 KK11 KK12 KK13 KK14 KK15 KK16 KK17 KK18 KK19 KK20 KK22 KK23 KK24 KK25 KK26 KK27 KK28 KK29 KK30 KK31 KK32 KK33 KK34 KK35 KK36 KK37 KK38 KK39 KK40 KK41 KK42 KK43 KK44 KK47 KK50 KK51


	do
	cd $hdrimg_dir
	
	#mri_convert -i $subj*"MPRAGE".hdr -it nifti1 -ot nii -o $output_dir/$subj"_T1".nii
	mri_convert -i $subj*"_QSM".hdr -it nifti1 -ot nii -o $output_dir/$subj"_QSM_mag".nii
	mri_convert -i $subj*"_QSM_phase".hdr -it nifti1 -ot nii -o $output_dir/$subj"_QSM_phase".nii

done
